from __future__ import annotations

"""UV postprocessing — packing, margin, and export."""

from pathlib import Path

import numpy as np
import torch


def pack_uv_charts(
    uv_coords: np.ndarray,
    method: str = "greedy",
    padding: float = 0.01,
) -> np.ndarray:
    """Pack UV charts into [0, 1] x [0, 1] atlas space.

    Args:
        uv_coords: (N, 2) UV coordinates (may extend outside [0,1])
        method: 'greedy' or 'xatlas'
        padding: padding between charts

    Returns:
        Packed UV coordinates in [0, 1] x [0, 1]
    """
    uv = uv_coords.copy()

    # Normalize to [0, 1]
    uv_min = uv.min(axis=0)
    uv_max = uv.max(axis=0)
    extent = uv_max - uv_min
    extent = np.maximum(extent, 1e-8)
    uv = (uv - uv_min) / extent

    # Apply padding
    uv = uv * (1.0 - 2 * padding) + padding

    return uv


def add_uv_margins(
    uv_coords: np.ndarray,
    faces: np.ndarray,
    margin: float = 0.005,
) -> np.ndarray:
    """Slightly expand UV islands to prevent texture bleeding.

    Moves UV coordinates outward from face centroids by a small margin.
    """
    result = uv_coords.copy()

    for face in faces:
        centroid = result[face].mean(axis=0)
        for vi in face:
            direction = result[vi] - centroid
            direction_len = np.linalg.norm(direction)
            if direction_len > 1e-8:
                result[vi] += direction / direction_len * margin

    return result


def export_uv_mesh(
    path: str | Path,
    vertices: np.ndarray,
    uv_coords: np.ndarray,
    faces: np.ndarray,
):
    """Export mesh with UV coordinates to OBJ file.

    Args:
        path: output file path
        vertices: (V, 3) vertex positions
        uv_coords: (V, 2) UV coordinates
        faces: (F, 3) face vertex indices
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    with open(path, "w") as f:
        f.write("# Generated by ML UV Unwrap\n")
        f.write(f"# Vertices: {len(vertices)}, UVs: {len(uv_coords)}, Faces: {len(faces)}\n\n")

        # Vertices
        for v in vertices:
            f.write(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")

        f.write("\n")

        # UV coordinates
        for uv in uv_coords:
            f.write(f"vt {uv[0]:.6f} {uv[1]:.6f}\n")

        f.write("\n")

        # Faces (1-indexed in OBJ)
        for face in faces:
            indices = " ".join(f"{vi + 1}/{vi + 1}" for vi in face)
            f.write(f"f {indices}\n")

    print(f"Exported UV mesh to {path}")
    print(f"  Vertices: {len(vertices)}")
    print(f"  UV coords: {len(uv_coords)}")
    print(f"  Faces: {len(faces)}")
